name: cormorant
baseurl: /cormorant
description: CSV Library for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.0+16-656e7a39-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
