name: cormorant
baseurl: /cormorant
description: CSV Library for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.0+73-aaa4fb2c-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
