name: cormorant
baseurl: /cormorant
description: CSV Library for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.0+58-12a7923b-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
