name: cormorant
baseurl: /cormorant
description: CSV Library for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.0+65-1796f7b7-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
