name: cormorant
baseurl: /cormorant
description: CSV Library for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.0+34-5d0e0dce-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
