name: cormorant
baseurl: /cormorant
description: CSV Library for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.0+77-451614a1-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
