name: cormorant
baseurl: /cormorant
description: CSV Library for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.0+36-6ecf8d9f-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
