name: cormorant
baseurl: /cormorant
description: CSV Library for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.0-M6+16-704bf145-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
