name: cormorant
baseurl: /cormorant
description: CSV Library for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.0+28-5044f12e-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
