name: cormorant
baseurl: /cormorant
description: CSV Library for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.0+52-f8ea4ae8-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
